import os
import re
from datetime import datetime
from prov.model import ProvDocument
from prov.dot import prov_to_dot
from starlette.background import BackgroundTask
from fastapi.responses import FileResponse
from fastapi import APIRouter, Depends
from schema.prov import Entity, Activity, Agent
from schema.init_db import session
from schema.workflow_execution import WorkflowExecution, WorkflowExecutionStep, StepResourceUsage, ExecutionEnvironment
from schema.workflow_registry import WorkflowRegistry
from authentication.auth import authenticate_user
from models.user import User
from ruamel.yaml import YAML
from models.response import Response
from sqlalchemy.exc import SQLAlchemyError
import json

router = APIRouter()


def _resolve_cwl_files(spec):
    """Parse CWL spec to resolve file relationships between steps.

    Returns:
        file_entities: dict of {filename: entity_type} — all files involved
        step_inputs:   dict of {step_name: [filename, ...]} — files used by each step
        step_outputs:  dict of {step_name: [filename, ...]} — files generated by each step
    """
    # Collect top-level input defaults for resolving $(inputs.X) globs
    input_defaults = {}
    for inp in spec.get('inputs', []):
        if 'default' in inp:
            input_defaults[inp['id']] = inp['default']

    # Resolve each step's output globs to filenames
    # output_map: {step_name/output_id: filename}
    output_map = {}
    for step_name, step in spec.get('steps', {}).items():
        if step_name == 'map':
            continue
        run = step['run']
        step_in = step.get('in', {})
        for out in run.get('outputs', []):
            if out.get('type') != 'File':
                continue
            glob = out.get('outputBinding', {}).get('glob', '')
            if '$(inputs.' in glob:
                run_input_name = glob.split('$(inputs.')[-1].rstrip(')')
                # Resolve: run input → step in mapping → top-level input default
                source = step_in.get(run_input_name, run_input_name)
                if '/' not in source:
                    filename = input_defaults.get(source, glob)
                else:
                    filename = glob
            else:
                filename = glob
            output_map[f"{step_name}/{out['id']}"] = filename

    # Build per-step input/output file lists
    step_inputs = {}
    step_outputs = {}
    file_entities = {}

    for step_name, step in spec.get('steps', {}).items():
        if step_name == 'map':
            continue
        run = step['run']
        step_in = step.get('in', {})

        # Outputs
        step_outputs[step_name] = []
        for out in run.get('outputs', []):
            if out.get('type') != 'File':
                continue
            key = f"{step_name}/{out['id']}"
            filename = output_map.get(key, out['id'])
            step_outputs[step_name].append(filename)
            file_entities[filename] = 'workflow_intermediate_result_file'

        # Inputs (File type only)
        step_inputs[step_name] = []
        run_inputs = run.get('inputs', {})
        for input_name, input_type in run_inputs.items():
            if input_type != 'File':
                continue
            source = step_in.get(input_name, '')
            if '/' in source:
                # From another step's output
                filename = output_map.get(source, input_name)
                step_inputs[step_name].append(filename)

    # Mark final output files
    for out in spec.get('outputs', []):
        if out.get('type') != 'File':
            continue
        source = out.get('outputSource', '')
        filename = output_map.get(source)
        if filename:
            file_entities[filename] = 'workflow_final_result_file'

    return file_entities, step_inputs, step_outputs


@router.get(
    "/capture/{execution_id}",
    description="Capture provenance for workflow with specific execution_id",
)
async def track_provenance(
    execution_id: int,
    user: User = Depends(authenticate_user)
):
    try:
        workflow_execution = session.query(WorkflowExecution).filter(
            WorkflowExecution.id == execution_id
        ).first()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )

    if workflow_execution is None:
        return Response(
            success=False,
            message="Invalid execution_id",
            error_code=404,
            data={}
        )

    execution_status = workflow_execution.status
    if execution_status not in ('finished', 'failed'):
        return Response(
            success=False,
            message="Workflow must be finished or failed in order to capture provenance",
            error_code=409,
            data={}
        )

    try:
        previously_captured = session.query(Activity).filter(Activity.workflow_execution_id == workflow_execution.id).first()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )
    
    if previously_captured:
        return Response(
            success=False,
            message="Provenance was captured before",
            error_code=403,
            data={}
        )

    try:
        workflow_spec_file = session.query(WorkflowRegistry).filter(WorkflowRegistry.id == workflow_execution.registry_id).first().spec_file_content
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )

    yaml = YAML(typ='safe', pure=True)
    spec_file_yaml = yaml.load(workflow_spec_file)
    
    try:
        workflow_execution_steps = session.query(WorkflowExecutionStep).filter(WorkflowExecutionStep.workflow_execution_id == workflow_execution.id).all()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )

    # Resolve file relationships from the CWL spec
    file_entities_map, cwl_step_inputs, cwl_step_outputs = _resolve_cwl_files(spec_file_yaml)

    # Create workflow entity
    workflow_entity = Entity(
        type='workflow',
        path=f"{workflow_execution.reana_id}/workflow.json",
        name='workflow',
        workflow_execution_id=workflow_execution.id
    )

    # Create file entities from CWL spec
    file_entity_objects = {}
    for filename, file_type in file_entities_map.items():
        entity = Entity(
            type=file_type,
            path=filename,
            name=filename,
            workflow_execution_id=workflow_execution.id
        )
        file_entity_objects[filename] = entity

    entities = [workflow_entity] + list(file_entity_objects.values())

    # Create step activities with status from execution steps
    step_activities = [
        Activity(
            type='step_execution',
            name=s.name.replace(':', '_'),
            status=s.status,
            start_time=s.start_time,
            end_time=s.end_time,
            workflow_execution_id=workflow_execution.id
        ) for s in workflow_execution_steps if s.name != 'map'
    ]
    workflow_activity = Activity(
        type='workflow_execution',
        name=f"{workflow_execution.reana_name.replace(':','_')}_{workflow_execution.reana_run_number}",
        status=execution_status,
        start_time=workflow_execution.start_time,
        end_time=workflow_execution.end_time,
        workflow_execution_id=workflow_execution.id
    )
    activities = [workflow_activity] + step_activities

    try:
        for e in entities:
            session.add(e)
        for a in activities:
            session.add(a)
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )

    # Link file entities to step activities (used/generated relationships)
    for step_act in step_activities:
        step_name = step_act.name

        # Link input files (used by step)
        for filename in cwl_step_inputs.get(step_name, []):
            entity = file_entity_objects.get(filename)
            if entity:
                step_act.used.append(entity)

        # Link output files (generated by step) — only for completed steps
        if step_act.status != 'failed':
            for filename in cwl_step_outputs.get(step_name, []):
                entity = file_entity_objects.get(filename)
                if entity:
                    step_act.generated.append(entity)

        try:
            session.add(step_act)
        except SQLAlchemyError as e:
            session.rollback()
            return Response(
                success=False,
                message=f"Database error: {str(e)}",
                error_code=500,
                data={}
            )

    # Link final output entities to workflow activity (only for finished workflows)
    if execution_status == 'finished':
        for filename, file_type in file_entities_map.items():
            if file_type == 'workflow_final_result_file':
                entity = file_entity_objects.get(filename)
                if entity:
                    workflow_activity.generated.append(entity)
        try:
            session.add(workflow_activity)
        except SQLAlchemyError as e:
            session.rollback()
            return Response(
                success=False,
                message=f"Database error: {str(e)}",
                error_code=500,
                data={}
            )

    try:
        session.add(workflow_entity)
        agent = Agent(
            type='person',
            name=workflow_execution.username,
            workflow_execution_id=workflow_execution.id
        )
        session.add(agent)

        software = Agent(
            type='software',
            name='software executing experiments',
            workflow_execution_id=workflow_execution.id
        )
        session.add(software)

        session.commit()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )

    # Build response data summarizing what was captured
    failed_steps = [s.name for s in workflow_execution_steps if s.status == 'failed']
    response_data = {
        'workflow_status': execution_status,
        'total_steps': len([s for s in workflow_execution_steps if s.name != 'map']),
        'failed_steps': failed_steps,
        'has_detailed_provenance': len(file_entities_map) > 0,
    }

    return Response(
        success=True,
        message='Provenance captured successfully',
        data=response_data
    )


@router.get(
    "/draw/{execution_id}",
    description="Create a graphical representation of provenance for workflow with specific execution id",
)
async def draw_provenance(
    execution_id: int,
    user: User = Depends(authenticate_user)
):
    try:
        workflow_execution = session.query(WorkflowExecution).filter(
            WorkflowExecution.id == execution_id
        ).first()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )

    if workflow_execution is None:
        return Response(
            success=False,
            message="Invalid execution_id",
            error_code=404,
            data={}
        )

    try:
        activities = session.query(Activity).filter(
            Activity.workflow_execution_id == workflow_execution.id
        ).all()

        workflow_entity = session.query(Entity).filter(
            Entity.workflow_execution_id == workflow_execution.id,
            Entity.type == 'workflow'
        ).first()

        workflow_activity = session.query(Activity).filter(
            Activity.workflow_execution_id == workflow_execution.id,
            Activity.type == 'workflow_execution'
        ).first()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )

    # Load resource usage for step activities
    step_resource_map = {}
    try:
        step_exec_records = session.query(WorkflowExecutionStep).filter(
            WorkflowExecutionStep.workflow_execution_id == workflow_execution.id
        ).all()
        for step_rec in step_exec_records:
            resource = session.query(StepResourceUsage).filter(
                StepResourceUsage.step_id == step_rec.id
            ).first()
            if resource:
                step_resource_map[step_rec.name.replace(':', '_')] = resource
    except SQLAlchemyError:
        session.rollback()

    doc = ProvDocument()
    doc.set_default_namespace('https://www.w3.org/TR/prov-dm/')

    # sort activities — handle None end_time (failed steps) by using start_time as fallback
    sorted_activities = sorted(activities, key=lambda x: x.end_time or x.start_time)
    for i, a in enumerate(sorted_activities, start=1):
        attrs = {
            'type': a.type,
            'status': a.status or 'unknown',
        }
        # Add resource usage to activity properties
        resource = step_resource_map.get(a.name.replace(':', '_'))
        if resource:
            if resource.cpu_time_seconds is not None:
                attrs['cpu_time'] = f"{round(resource.cpu_time_seconds, 1)}s"
            if resource.memory_peak_mb is not None:
                attrs['memory_peak_mb'] = round(resource.memory_peak_mb, 1)
            if resource.disk_read_bytes is not None and resource.disk_read_bytes > 0:
                attrs['disk_read_mb'] = round(resource.disk_read_bytes / (1024 * 1024), 1)
            if resource.disk_write_bytes is not None and resource.disk_write_bytes > 0:
                attrs['disk_write_mb'] = round(resource.disk_write_bytes / (1024 * 1024), 1)
            if resource.backend_job_id:
                attrs['backend_job_id'] = resource.backend_job_id
        # Add step-level info
        step_rec = next((s for s in step_exec_records if s.name == a.name), None)
        if step_rec:
            if step_rec.exit_code is not None:
                attrs['exit_code'] = step_rec.exit_code
            if step_rec.command:
                # Shorten REANA staging paths to just filenames for readability
                cmd = re.sub(r'/var/reana/[^\s]+/([^\s/]+)', r'\1', step_rec.command)
                attrs['command'] = cmd
            if step_rec.error_message:
                attrs['error_message'] = step_rec.error_message[:200]

        doc.activity(
            a.name.replace(':', '_'),
            a.start_time,
            a.end_time,
            attrs
        )

    doc.entity(
        workflow_entity.name,
        {
            'id': workflow_entity.id,
            'type': workflow_entity.type,
            'path': workflow_entity.path,
            'name': workflow_entity.name,
            'size': workflow_entity.size,
            'last_modified': workflow_entity.last_modified,
        }
    )

    for a in activities:
        for entity in a.used:
            doc.entity(
                entity.name,
                {
                    'id': entity.id,
                    'type': entity.type,
                    'path': entity.path,
                    'name': entity.name,
                    'size': entity.size,
                    'last_modified': entity.last_modified,
                }
            )

            doc.used(a.name, entity.name)

        for entity in a.generated:
            doc.entity(
                entity.name,
                {
                    'id': entity.id,
                    'type': entity.type,
                    'path': entity.path,
                    'name': entity.name,
                    'size': entity.size,
                    'last_modified': entity.last_modified,
                }
            )
            doc.generation(entity.name, a.name)

    doc.start(
        activity=sorted_activities[0].name,
        trigger=workflow_entity.name,
        other_attributes={
            'time': sorted_activities[0].start_time
        }
    )

    last_activity = sorted_activities[-1]
    if last_activity.end_time:
        doc.end(
            activity=last_activity.name,
            trigger=workflow_entity.name,
            other_attributes={
                'time': last_activity.end_time
            }
        )

    try:
        person = session.query(Agent).filter(
            Agent.workflow_execution_id == workflow_execution.id,
            Agent.type == 'person'
        ).first()

        software = session.query(Agent).filter(
            Agent.workflow_execution_id == workflow_execution.id,
            Agent.type == 'software'
        ).first()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(
            success=False,
            message=f"Database error: {str(e)}",
            error_code=500,
            data={}
        )

    doc.agent(
        person.name,
        {
            'type': 'person'
        }
    )

    doc.agent(
        software.name,
        {
            'type': 'software'
        }
    )

    doc.actedOnBehalfOf(
        delegate=software.name,
        responsible=person.name
    )
    doc.attribution(
        entity=workflow_entity.name,
        agent=software.name
    )

    doc.association(
        agent=software.name,
        activity=workflow_activity.name
    )

    # Add execution environment as an entity
    try:
        env = session.query(ExecutionEnvironment).filter(
            ExecutionEnvironment.workflow_execution_id == workflow_execution.id
        ).first()
    except SQLAlchemyError:
        session.rollback()
        env = None
    if env:
        env_attrs = {'type': 'execution_environment'}
        if env.reana_server_url:
            env_attrs['reana_server'] = env.reana_server_url
        if env.compute_backend:
            env_attrs['compute_backend'] = env.compute_backend
        if env.docker_image:
            env_attrs['docker_image'] = env.docker_image
        if env.kubernetes_memory_limit:
            env_attrs['k8s_memory_limit'] = env.kubernetes_memory_limit
        doc.entity('execution_environment', env_attrs)
        doc.used(workflow_activity.name, 'execution_environment')

    png_name = f"{workflow_execution.reana_name}:{workflow_execution.reana_run_number}-provenance.png"
    dot = prov_to_dot(doc)

    # Color failed activity nodes red — prov_to_dot uses internal names (n1, n2...)
    # so we match via label text
    failed_names = {a.name.replace(':', '_') for a in activities if a.status == 'failed'}
    for node in dot.get_nodes():
        label = node.get_label()
        if not label:
            continue
        label_text = label.strip('"')
        if label_text in failed_names:
            node.set_fillcolor('#ff9999')
            node.set_style('filled')

    dot.write_png(png_name)

    def _delete_png_file():
        os.unlink(png_name)

    return FileResponse(
        png_name,
        filename=png_name,
        background=BackgroundTask(_delete_png_file),
    )


@router.get(
    "/json/{execution_id}",
    description="Export provenance for a workflow execution as W3C PROV-JSON",
)
async def export_provenance_json(
    execution_id: int,
    user: User = Depends(authenticate_user)
):
    try:
        workflow_execution = session.query(WorkflowExecution).filter(
            WorkflowExecution.id == execution_id
        ).first()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(success=False, message=f"Database error: {str(e)}", error_code=500, data={})

    if workflow_execution is None:
        return Response(success=False, message="Invalid execution_id", error_code=404, data={})

    try:
        activities = session.query(Activity).filter(Activity.workflow_execution_id == execution_id).all()
        entities = session.query(Entity).filter(Entity.workflow_execution_id == execution_id).all()
        agents = session.query(Agent).filter(Agent.workflow_execution_id == execution_id).all()
        steps = session.query(WorkflowExecutionStep).filter(
            WorkflowExecutionStep.workflow_execution_id == execution_id
        ).all()
    except SQLAlchemyError as e:
        session.rollback()
        return Response(success=False, message=f"Database error: {str(e)}", error_code=500, data={})

    if not activities:
        return Response(success=False, message="No provenance captured yet. Call /capture/{execution_id} first.", error_code=404, data={})

    # Build W3C PROV-JSON document
    prov_doc = {
        "prefix": {
            "prov": "http://www.w3.org/ns/prov#",
            "xsd": "http://www.w3.org/2000/10/XMLSchema#",
            "reprov": "https://reprov.2ai.nip.io/ns#"
        },
        "entity": {},
        "activity": {},
        "agent": {},
        "wasGeneratedBy": {},
        "used": {},
        "wasAssociatedWith": {},
        "wasAttributedTo": {},
        "actedOnBehalfOf": {},
        "wasStartedBy": {},
        "wasEndedBy": {},
    }

    # Agents
    for ag in agents:
        prov_doc["agent"][f"reprov:{ag.name}"] = {
            "prov:type": ag.type
        }

    # Delegation
    person = next((a for a in agents if a.type == 'person'), None)
    software = next((a for a in agents if a.type == 'software'), None)
    if person and software:
        prov_doc["actedOnBehalfOf"]["_:d1"] = {
            "prov:delegate": f"reprov:{software.name}",
            "prov:responsible": f"reprov:{person.name}"
        }

    # Entities
    for e in entities:
        prov_doc["entity"][f"reprov:{e.name}"] = {
            "prov:type": e.type,
            "reprov:path": e.path,
            "reprov:size": e.size,
            "reprov:lastModified": e.last_modified.isoformat() if e.last_modified else None
        }

    # Environment entity
    try:
        env = session.query(ExecutionEnvironment).filter(
            ExecutionEnvironment.workflow_execution_id == execution_id
        ).first()
    except SQLAlchemyError:
        session.rollback()
        env = None
    if env:
        env_data = {"prov:type": "reprov:ExecutionEnvironment"}
        if env.reana_server_url:
            env_data["reprov:reanaServer"] = env.reana_server_url
        if env.reana_workflow_url:
            env_data["reprov:reanaWorkflowUrl"] = env.reana_workflow_url
        if env.compute_backend:
            env_data["reprov:computeBackend"] = env.compute_backend
        if env.docker_image:
            env_data["reprov:dockerImage"] = env.docker_image
        if env.kubernetes_memory_limit:
            env_data["reprov:kubernetesMemoryLimit"] = env.kubernetes_memory_limit
        prov_doc["entity"]["reprov:execution_environment"] = env_data

    # Activities
    gen_counter = 0
    use_counter = 0
    assoc_counter = 0

    workflow_activity = next((a for a in activities if a.type == 'workflow_execution'), None)

    for a in activities:
        activity_id = f"reprov:{a.name.replace(':', '_')}"
        activity_data = {
            "prov:startTime": a.start_time.isoformat() if a.start_time else None,
            "prov:endTime": a.end_time.isoformat() if a.end_time else None,
            "prov:type": a.type,
            "reprov:status": a.status,
        }

        # Add step-level details
        step_rec = next((s for s in steps if s.name == a.name), None)
        if step_rec:
            activity_data["reprov:exitCode"] = step_rec.exit_code
            activity_data["reprov:command"] = step_rec.command
            if step_rec.error_message:
                activity_data["reprov:errorMessage"] = step_rec.error_message

            try:
                resource = session.query(StepResourceUsage).filter(
                    StepResourceUsage.step_id == step_rec.id
                ).first()
            except SQLAlchemyError:
                session.rollback()
                resource = None
            if resource:
                if resource.cpu_time_seconds is not None:
                    activity_data["reprov:cpuTimeSeconds"] = round(resource.cpu_time_seconds, 3)
                if resource.memory_peak_mb is not None:
                    activity_data["reprov:memoryPeakMB"] = round(resource.memory_peak_mb, 2)
                if resource.disk_read_bytes is not None:
                    activity_data["reprov:diskReadBytes"] = resource.disk_read_bytes
                if resource.disk_write_bytes is not None:
                    activity_data["reprov:diskWriteBytes"] = resource.disk_write_bytes
                if resource.backend_job_id:
                    activity_data["reprov:backendJobId"] = resource.backend_job_id

        prov_doc["activity"][activity_id] = activity_data

        # Association (software agent associated with workflow activity)
        if a.type == 'workflow_execution' and software:
            prov_doc["wasAssociatedWith"][f"_:wAW{assoc_counter}"] = {
                "prov:activity": activity_id,
                "prov:agent": f"reprov:{software.name}",
            }
            assoc_counter += 1

        # Used / wasGeneratedBy relations
        for used_entity in a.used:
            prov_doc["used"][f"_:u{use_counter}"] = {
                "prov:activity": activity_id,
                "prov:entity": f"reprov:{used_entity.name}"
            }
            use_counter += 1

        for gen_entity in a.generated:
            prov_doc["wasGeneratedBy"][f"_:wGB{gen_counter}"] = {
                "prov:entity": f"reprov:{gen_entity.name}",
                "prov:activity": activity_id
            }
            gen_counter += 1

    # Environment used by workflow activity
    if env and workflow_activity:
        prov_doc["used"][f"_:u{use_counter}"] = {
            "prov:activity": f"reprov:{workflow_activity.name.replace(':', '_')}",
            "prov:entity": "reprov:execution_environment"
        }

    # Attribution
    if software:
        workflow_entity = next((e for e in entities if e.type == 'workflow'), None)
        if workflow_entity:
            prov_doc["wasAttributedTo"]["_:wAT1"] = {
                "prov:entity": f"reprov:{workflow_entity.name}",
                "prov:agent": f"reprov:{software.name}"
            }

    # Start/End
    sorted_acts = sorted(activities, key=lambda x: x.end_time or x.start_time)
    if sorted_acts:
        first = sorted_acts[0]
        prov_doc["wasStartedBy"]["_:wSB1"] = {
            "prov:activity": f"reprov:{first.name.replace(':', '_')}",
            "prov:time": first.start_time.isoformat() if first.start_time else None
        }
        last = sorted_acts[-1]
        if last.end_time:
            prov_doc["wasEndedBy"]["_:wEB1"] = {
                "prov:activity": f"reprov:{last.name.replace(':', '_')}",
                "prov:time": last.end_time.isoformat()
            }

    # Remove empty sections
    prov_doc = {k: v for k, v in prov_doc.items() if v}

    return prov_doc
